spring:
  application:
      name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**

        - id: exam-service
          uri: lb://exam-service
          predicates:
            - Path=/exam/**

        - id: user-interface
          uri: lb://user-interface
          predicates:
            - Path=/ui/**


server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
app:
  swagger:
    enabled: true