spring:
  application:
      name: api-gateway
  cloud:
    gateway:
      routes:
#        - id: user-interface
#          uri: lb://user-interface
#          predicates:
#            - Path=/user-interface/**
#          filters:
#            - StripPrefix=1

# Path: User-Interface/src/main/resources/application.yml
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/**
#          filters:
#            - StripPrefix=1

server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
